version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: '1.23'

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic
    - funlen
    - goconst
    - lll
    - nakedret
    - whitespace

  settings:
    goconst:
      min-len: 2
      min-occurrences: 2

    misspell:
      locale: US

    lll:
      line-length: 140

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc

    funlen:
      lines: 200
      statements: -1

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gocyclo
          - errcheck

      - path: cmd/
        linters:
          - gochecknoinits

      - linters:
          - lll
        source: "^//go:generate "

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/dreamer-zq/DKNet

issues:
  max-issues-per-linter: 50
  max-same-issues: 3 