// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/health/v1/health.proto

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health status enumeration
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED     HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING         HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING     HealthStatus = 2
	HealthStatus_HEALTH_STATUS_SERVICE_UNKNOWN HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_SERVICE_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED":     0,
		"HEALTH_STATUS_SERVING":         1,
		"HEALTH_STATUS_NOT_SERVING":     2,
		"HEALTH_STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_health_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_proto_health_v1_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_health_v1_health_proto_rawDescGZIP(), []int{0}
}

// CheckRequest represents a health check request
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name to check (empty for overall health)
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_health_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// CheckResponse represents a health check response
type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current health status
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=health.v1.HealthStatus" json:"status,omitempty"`
	// Timestamp of the health check
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional additional details about the health status
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// Service-specific health information
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_health_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *CheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CheckResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CheckResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// WatchRequest represents a watch health request
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name to watch (empty for overall health)
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_health_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_health_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// WatchResponse represents a streaming health check response
type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current health status
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=health.v1.HealthStatus" json:"status,omitempty"`
	// Timestamp of the health check
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional additional details about the health status
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// Service-specific health information
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_proto_health_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_health_v1_health_proto_rawDescGZIP(), []int{3}
}

func (x *WatchResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *WatchResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WatchResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *WatchResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_health_v1_health_proto protoreflect.FileDescriptor

const file_proto_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/health/v1/health.proto\x12\thealth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\fCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x95\x02\n" +
	"\rCheckResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.health.v1.HealthStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.health.v1.CheckResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\fWatchRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x95\x02\n" +
	"\rWatchResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.health.v1.HealthStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.health.v1.WatchResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8a\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12!\n" +
	"\x1dHEALTH_STATUS_SERVICE_UNKNOWN\x10\x032\x89\x01\n" +
	"\rHealthService\x12:\n" +
	"\x05Check\x12\x17.health.v1.CheckRequest\x1a\x18.health.v1.CheckResponse\x12<\n" +
	"\x05Watch\x12\x17.health.v1.WatchRequest\x1a\x18.health.v1.WatchResponse0\x01B6Z4github.com/dreamer-zq/DKNet/proto/health/v1;healthv1b\x06proto3"

var (
	file_proto_health_v1_health_proto_rawDescOnce sync.Once
	file_proto_health_v1_health_proto_rawDescData []byte
)

func file_proto_health_v1_health_proto_rawDescGZIP() []byte {
	file_proto_health_v1_health_proto_rawDescOnce.Do(func() {
		file_proto_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_health_v1_health_proto_rawDesc), len(file_proto_health_v1_health_proto_rawDesc)))
	})
	return file_proto_health_v1_health_proto_rawDescData
}

var file_proto_health_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_health_v1_health_proto_goTypes = []any{
	(HealthStatus)(0),             // 0: health.v1.HealthStatus
	(*CheckRequest)(nil),          // 1: health.v1.CheckRequest
	(*CheckResponse)(nil),         // 2: health.v1.CheckResponse
	(*WatchRequest)(nil),          // 3: health.v1.WatchRequest
	(*WatchResponse)(nil),         // 4: health.v1.WatchResponse
	nil,                           // 5: health.v1.CheckResponse.MetadataEntry
	nil,                           // 6: health.v1.WatchResponse.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_health_v1_health_proto_depIdxs = []int32{
	0, // 0: health.v1.CheckResponse.status:type_name -> health.v1.HealthStatus
	7, // 1: health.v1.CheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	5, // 2: health.v1.CheckResponse.metadata:type_name -> health.v1.CheckResponse.MetadataEntry
	0, // 3: health.v1.WatchResponse.status:type_name -> health.v1.HealthStatus
	7, // 4: health.v1.WatchResponse.timestamp:type_name -> google.protobuf.Timestamp
	6, // 5: health.v1.WatchResponse.metadata:type_name -> health.v1.WatchResponse.MetadataEntry
	1, // 6: health.v1.HealthService.Check:input_type -> health.v1.CheckRequest
	3, // 7: health.v1.HealthService.Watch:input_type -> health.v1.WatchRequest
	2, // 8: health.v1.HealthService.Check:output_type -> health.v1.CheckResponse
	4, // 9: health.v1.HealthService.Watch:output_type -> health.v1.WatchResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_health_v1_health_proto_init() }
func file_proto_health_v1_health_proto_init() {
	if File_proto_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_health_v1_health_proto_rawDesc), len(file_proto_health_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_health_v1_health_proto_goTypes,
		DependencyIndexes: file_proto_health_v1_health_proto_depIdxs,
		EnumInfos:         file_proto_health_v1_health_proto_enumTypes,
		MessageInfos:      file_proto_health_v1_health_proto_msgTypes,
	}.Build()
	File_proto_health_v1_health_proto = out.File
	file_proto_health_v1_health_proto_goTypes = nil
	file_proto_health_v1_health_proto_depIdxs = nil
}
