// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/tss/v1/tss.proto

package tssv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation status enumeration
type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_IN_PROGRESS OperationStatus = 2
	OperationStatus_OPERATION_STATUS_COMPLETED   OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 4
	OperationStatus_OPERATION_STATUS_CANCELED    OperationStatus = 5
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_IN_PROGRESS",
		3: "OPERATION_STATUS_COMPLETED",
		4: "OPERATION_STATUS_FAILED",
		5: "OPERATION_STATUS_CANCELED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_IN_PROGRESS": 2,
		"OPERATION_STATUS_COMPLETED":   3,
		"OPERATION_STATUS_FAILED":      4,
		"OPERATION_STATUS_CANCELED":    5,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tss_v1_tss_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_proto_tss_v1_tss_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{0}
}

// Operation type enumeration
type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_KEYGEN      OperationType = 1
	OperationType_OPERATION_TYPE_SIGNING     OperationType = 2
	OperationType_OPERATION_TYPE_RESHARING   OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_KEYGEN",
		2: "OPERATION_TYPE_SIGNING",
		3: "OPERATION_TYPE_RESHARING",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_KEYGEN":      1,
		"OPERATION_TYPE_SIGNING":     2,
		"OPERATION_TYPE_RESHARING":   3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tss_v1_tss_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_tss_v1_tss_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{1}
}

// StartKeygenRequest represents a key generation request
type StartKeygenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional operation ID provided by client for idempotency
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Number of parties required to sign (threshold)
	Threshold int32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Total number of parties involved
	Parties int32 `protobuf:"varint,3,opt,name=parties,proto3" json:"parties,omitempty"`
	// List of participant peer IDs
	Participants  []string `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKeygenRequest) Reset() {
	*x = StartKeygenRequest{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKeygenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKeygenRequest) ProtoMessage() {}

func (x *StartKeygenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKeygenRequest.ProtoReflect.Descriptor instead.
func (*StartKeygenRequest) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{0}
}

func (x *StartKeygenRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StartKeygenRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartKeygenRequest) GetParties() int32 {
	if x != nil {
		return x.Parties
	}
	return 0
}

func (x *StartKeygenRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

// StartKeygenResponse represents the response when starting keygen operation
type StartKeygenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique operation identifier
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Current status of the operation
	Status OperationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=tss.v1.OperationStatus" json:"status,omitempty"`
	// Timestamp when operation was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKeygenResponse) Reset() {
	*x = StartKeygenResponse{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKeygenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKeygenResponse) ProtoMessage() {}

func (x *StartKeygenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKeygenResponse.ProtoReflect.Descriptor instead.
func (*StartKeygenResponse) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{1}
}

func (x *StartKeygenResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StartKeygenResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *StartKeygenResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// KeygenResult represents the result of key generation
type KeygenResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated public key in hex format
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Unique identifier for the generated key
	KeyId         string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenResult) Reset() {
	*x = KeygenResult{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenResult) ProtoMessage() {}

func (x *KeygenResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenResult.ProtoReflect.Descriptor instead.
func (*KeygenResult) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{2}
}

func (x *KeygenResult) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KeygenResult) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// StartSigningRequest represents a signing request
type StartSigningRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional operation ID provided by client for idempotency
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Message to be signed (bytes)
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Key ID to use for signing
	KeyId string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// List of participant peer IDs
	Participants  []string `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSigningRequest) Reset() {
	*x = StartSigningRequest{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSigningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSigningRequest) ProtoMessage() {}

func (x *StartSigningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSigningRequest.ProtoReflect.Descriptor instead.
func (*StartSigningRequest) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{3}
}

func (x *StartSigningRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StartSigningRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StartSigningRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartSigningRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

// StartSigningResponse represents the response when starting signing operation
type StartSigningResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique operation identifier
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Current status of the operation
	Status OperationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=tss.v1.OperationStatus" json:"status,omitempty"`
	// Timestamp when operation was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSigningResponse) Reset() {
	*x = StartSigningResponse{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSigningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSigningResponse) ProtoMessage() {}

func (x *StartSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSigningResponse.ProtoReflect.Descriptor instead.
func (*StartSigningResponse) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{4}
}

func (x *StartSigningResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StartSigningResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *StartSigningResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SigningResult represents the result of signing operation
type SigningResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Complete signature in hex format
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// R component of the signature
	R string `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	// S component of the signature
	S             string `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningResult) Reset() {
	*x = SigningResult{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningResult) ProtoMessage() {}

func (x *SigningResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningResult.ProtoReflect.Descriptor instead.
func (*SigningResult) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{5}
}

func (x *SigningResult) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SigningResult) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *SigningResult) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// StartResharingRequest represents a resharing request
type StartResharingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional operation ID provided by client for idempotency
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Key ID to reshare
	KeyId string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// New threshold value
	NewThreshold int32 `protobuf:"varint,3,opt,name=new_threshold,json=newThreshold,proto3" json:"new_threshold,omitempty"`
	// New total number of parties
	NewParties int32 `protobuf:"varint,4,opt,name=new_parties,json=newParties,proto3" json:"new_parties,omitempty"`
	// List of old participant peer IDs
	OldParticipants []string `protobuf:"bytes,5,rep,name=old_participants,json=oldParticipants,proto3" json:"old_participants,omitempty"`
	// List of new participant peer IDs
	NewParticipants []string `protobuf:"bytes,6,rep,name=new_participants,json=newParticipants,proto3" json:"new_participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartResharingRequest) Reset() {
	*x = StartResharingRequest{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResharingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResharingRequest) ProtoMessage() {}

func (x *StartResharingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResharingRequest.ProtoReflect.Descriptor instead.
func (*StartResharingRequest) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{6}
}

func (x *StartResharingRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StartResharingRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartResharingRequest) GetNewThreshold() int32 {
	if x != nil {
		return x.NewThreshold
	}
	return 0
}

func (x *StartResharingRequest) GetNewParties() int32 {
	if x != nil {
		return x.NewParties
	}
	return 0
}

func (x *StartResharingRequest) GetOldParticipants() []string {
	if x != nil {
		return x.OldParticipants
	}
	return nil
}

func (x *StartResharingRequest) GetNewParticipants() []string {
	if x != nil {
		return x.NewParticipants
	}
	return nil
}

// StartResharingResponse represents the response when starting resharing operation
type StartResharingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique operation identifier
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Current status of the operation
	Status OperationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=tss.v1.OperationStatus" json:"status,omitempty"`
	// Timestamp when operation was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResharingResponse) Reset() {
	*x = StartResharingResponse{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResharingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResharingResponse) ProtoMessage() {}

func (x *StartResharingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResharingResponse.ProtoReflect.Descriptor instead.
func (*StartResharingResponse) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{7}
}

func (x *StartResharingResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *StartResharingResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *StartResharingResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetOperationRequest represents a request to get operation status
type GetOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation ID to query
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{8}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// GetOperationResponse represents the detailed status of an operation
type GetOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation identifier
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Type of operation
	Type OperationType `protobuf:"varint,2,opt,name=type,proto3,enum=tss.v1.OperationType" json:"type,omitempty"`
	// Session ID for the operation
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Current status
	Status OperationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=tss.v1.OperationStatus" json:"status,omitempty"`
	// List of participants
	Participants []string `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	// Timestamp when operation was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when operation completed (if applicable)
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	// Error message if operation failed
	Error *string `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Operation result (one of the result types)
	//
	// Types that are valid to be assigned to Result:
	//
	//	*GetOperationResponse_KeygenResult
	//	*GetOperationResponse_SigningResult
	//	*GetOperationResponse_ResharingResult
	Result isGetOperationResponse_Result `protobuf_oneof:"result"`
	// Original request (one of the request types)
	//
	// Types that are valid to be assigned to Request:
	//
	//	*GetOperationResponse_KeygenRequest
	//	*GetOperationResponse_SigningRequest
	//	*GetOperationResponse_ResharingRequest
	Request       isGetOperationResponse_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_proto_tss_v1_tss_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tss_v1_tss_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_tss_v1_tss_proto_rawDescGZIP(), []int{9}
}

func (x *GetOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetOperationResponse) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *GetOperationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetOperationResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetOperationResponse) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetOperationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetOperationResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *GetOperationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetOperationResponse) GetResult() isGetOperationResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetOperationResponse) GetKeygenResult() *KeygenResult {
	if x != nil {
		if x, ok := x.Result.(*GetOperationResponse_KeygenResult); ok {
			return x.KeygenResult
		}
	}
	return nil
}

func (x *GetOperationResponse) GetSigningResult() *SigningResult {
	if x != nil {
		if x, ok := x.Result.(*GetOperationResponse_SigningResult); ok {
			return x.SigningResult
		}
	}
	return nil
}

func (x *GetOperationResponse) GetResharingResult() *KeygenResult {
	if x != nil {
		if x, ok := x.Result.(*GetOperationResponse_ResharingResult); ok {
			return x.ResharingResult
		}
	}
	return nil
}

func (x *GetOperationResponse) GetRequest() isGetOperationResponse_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetOperationResponse) GetKeygenRequest() *StartKeygenRequest {
	if x != nil {
		if x, ok := x.Request.(*GetOperationResponse_KeygenRequest); ok {
			return x.KeygenRequest
		}
	}
	return nil
}

func (x *GetOperationResponse) GetSigningRequest() *StartSigningRequest {
	if x != nil {
		if x, ok := x.Request.(*GetOperationResponse_SigningRequest); ok {
			return x.SigningRequest
		}
	}
	return nil
}

func (x *GetOperationResponse) GetResharingRequest() *StartResharingRequest {
	if x != nil {
		if x, ok := x.Request.(*GetOperationResponse_ResharingRequest); ok {
			return x.ResharingRequest
		}
	}
	return nil
}

type isGetOperationResponse_Result interface {
	isGetOperationResponse_Result()
}

type GetOperationResponse_KeygenResult struct {
	KeygenResult *KeygenResult `protobuf:"bytes,9,opt,name=keygen_result,json=keygenResult,proto3,oneof"`
}

type GetOperationResponse_SigningResult struct {
	SigningResult *SigningResult `protobuf:"bytes,10,opt,name=signing_result,json=signingResult,proto3,oneof"`
}

type GetOperationResponse_ResharingResult struct {
	ResharingResult *KeygenResult `protobuf:"bytes,11,opt,name=resharing_result,json=resharingResult,proto3,oneof"` // Resharing produces a new key
}

func (*GetOperationResponse_KeygenResult) isGetOperationResponse_Result() {}

func (*GetOperationResponse_SigningResult) isGetOperationResponse_Result() {}

func (*GetOperationResponse_ResharingResult) isGetOperationResponse_Result() {}

type isGetOperationResponse_Request interface {
	isGetOperationResponse_Request()
}

type GetOperationResponse_KeygenRequest struct {
	KeygenRequest *StartKeygenRequest `protobuf:"bytes,12,opt,name=keygen_request,json=keygenRequest,proto3,oneof"`
}

type GetOperationResponse_SigningRequest struct {
	SigningRequest *StartSigningRequest `protobuf:"bytes,13,opt,name=signing_request,json=signingRequest,proto3,oneof"`
}

type GetOperationResponse_ResharingRequest struct {
	ResharingRequest *StartResharingRequest `protobuf:"bytes,14,opt,name=resharing_request,json=resharingRequest,proto3,oneof"`
}

func (*GetOperationResponse_KeygenRequest) isGetOperationResponse_Request() {}

func (*GetOperationResponse_SigningRequest) isGetOperationResponse_Request() {}

func (*GetOperationResponse_ResharingRequest) isGetOperationResponse_Request() {}

var File_proto_tss_v1_tss_proto protoreflect.FileDescriptor

const file_proto_tss_v1_tss_proto_rawDesc = "" +
	"\n" +
	"\x16proto/tss/v1/tss.proto\x12\x06tss.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x12StartKeygenRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x05R\tthreshold\x12\x18\n" +
	"\aparties\x18\x03 \x01(\x05R\aparties\x12\"\n" +
	"\fparticipants\x18\x04 \x03(\tR\fparticipants\"\xa4\x01\n" +
	"\x13StartKeygenResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.tss.v1.OperationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"D\n" +
	"\fKeygenResult\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"\x8d\x01\n" +
	"\x13StartSigningRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\"\n" +
	"\fparticipants\x18\x04 \x03(\tR\fparticipants\"\xa5\x01\n" +
	"\x14StartSigningResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.tss.v1.OperationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"I\n" +
	"\rSigningResult\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\f\n" +
	"\x01r\x18\x02 \x01(\tR\x01r\x12\f\n" +
	"\x01s\x18\x03 \x01(\tR\x01s\"\xed\x01\n" +
	"\x15StartResharingRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12#\n" +
	"\rnew_threshold\x18\x03 \x01(\x05R\fnewThreshold\x12\x1f\n" +
	"\vnew_parties\x18\x04 \x01(\x05R\n" +
	"newParties\x12)\n" +
	"\x10old_participants\x18\x05 \x03(\tR\x0foldParticipants\x12)\n" +
	"\x10new_participants\x18\x06 \x03(\tR\x0fnewParticipants\"\xa7\x01\n" +
	"\x16StartResharingResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.tss.v1.OperationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\xbd\x06\n" +
	"\x14GetOperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.tss.v1.OperationTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.tss.v1.OperationStatusR\x06status\x12\"\n" +
	"\fparticipants\x18\x05 \x03(\tR\fparticipants\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vcompletedAt\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\b \x01(\tH\x03R\x05error\x88\x01\x01\x12;\n" +
	"\rkeygen_result\x18\t \x01(\v2\x14.tss.v1.KeygenResultH\x00R\fkeygenResult\x12>\n" +
	"\x0esigning_result\x18\n" +
	" \x01(\v2\x15.tss.v1.SigningResultH\x00R\rsigningResult\x12A\n" +
	"\x10resharing_result\x18\v \x01(\v2\x14.tss.v1.KeygenResultH\x00R\x0fresharingResult\x12C\n" +
	"\x0ekeygen_request\x18\f \x01(\v2\x1a.tss.v1.StartKeygenRequestH\x01R\rkeygenRequest\x12F\n" +
	"\x0fsigning_request\x18\r \x01(\v2\x1b.tss.v1.StartSigningRequestH\x01R\x0esigningRequest\x12L\n" +
	"\x11resharing_request\x18\x0e \x01(\v2\x1d.tss.v1.StartResharingRequestH\x01R\x10resharingRequestB\b\n" +
	"\x06resultB\t\n" +
	"\arequestB\x0f\n" +
	"\r_completed_atB\b\n" +
	"\x06_error*\xcf\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cOPERATION_STATUS_IN_PROGRESS\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19OPERATION_STATUS_CANCELED\x10\x05*\x84\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_KEYGEN\x10\x01\x12\x1a\n" +
	"\x16OPERATION_TYPE_SIGNING\x10\x02\x12\x1c\n" +
	"\x18OPERATION_TYPE_RESHARING\x10\x032\xbb\x02\n" +
	"\n" +
	"TSSService\x12F\n" +
	"\vStartKeygen\x12\x1a.tss.v1.StartKeygenRequest\x1a\x1b.tss.v1.StartKeygenResponse\x12I\n" +
	"\fStartSigning\x12\x1b.tss.v1.StartSigningRequest\x1a\x1c.tss.v1.StartSigningResponse\x12O\n" +
	"\x0eStartResharing\x12\x1d.tss.v1.StartResharingRequest\x1a\x1e.tss.v1.StartResharingResponse\x12I\n" +
	"\fGetOperation\x12\x1b.tss.v1.GetOperationRequest\x1a\x1c.tss.v1.GetOperationResponseB0Z.github.com/dreamer-zq/DKNet/proto/tss/v1;tssv1b\x06proto3"

var (
	file_proto_tss_v1_tss_proto_rawDescOnce sync.Once
	file_proto_tss_v1_tss_proto_rawDescData []byte
)

func file_proto_tss_v1_tss_proto_rawDescGZIP() []byte {
	file_proto_tss_v1_tss_proto_rawDescOnce.Do(func() {
		file_proto_tss_v1_tss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tss_v1_tss_proto_rawDesc), len(file_proto_tss_v1_tss_proto_rawDesc)))
	})
	return file_proto_tss_v1_tss_proto_rawDescData
}

var file_proto_tss_v1_tss_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_tss_v1_tss_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_tss_v1_tss_proto_goTypes = []any{
	(OperationStatus)(0),           // 0: tss.v1.OperationStatus
	(OperationType)(0),             // 1: tss.v1.OperationType
	(*StartKeygenRequest)(nil),     // 2: tss.v1.StartKeygenRequest
	(*StartKeygenResponse)(nil),    // 3: tss.v1.StartKeygenResponse
	(*KeygenResult)(nil),           // 4: tss.v1.KeygenResult
	(*StartSigningRequest)(nil),    // 5: tss.v1.StartSigningRequest
	(*StartSigningResponse)(nil),   // 6: tss.v1.StartSigningResponse
	(*SigningResult)(nil),          // 7: tss.v1.SigningResult
	(*StartResharingRequest)(nil),  // 8: tss.v1.StartResharingRequest
	(*StartResharingResponse)(nil), // 9: tss.v1.StartResharingResponse
	(*GetOperationRequest)(nil),    // 10: tss.v1.GetOperationRequest
	(*GetOperationResponse)(nil),   // 11: tss.v1.GetOperationResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_proto_tss_v1_tss_proto_depIdxs = []int32{
	0,  // 0: tss.v1.StartKeygenResponse.status:type_name -> tss.v1.OperationStatus
	12, // 1: tss.v1.StartKeygenResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tss.v1.StartSigningResponse.status:type_name -> tss.v1.OperationStatus
	12, // 3: tss.v1.StartSigningResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: tss.v1.StartResharingResponse.status:type_name -> tss.v1.OperationStatus
	12, // 5: tss.v1.StartResharingResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 6: tss.v1.GetOperationResponse.type:type_name -> tss.v1.OperationType
	0,  // 7: tss.v1.GetOperationResponse.status:type_name -> tss.v1.OperationStatus
	12, // 8: tss.v1.GetOperationResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 9: tss.v1.GetOperationResponse.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 10: tss.v1.GetOperationResponse.keygen_result:type_name -> tss.v1.KeygenResult
	7,  // 11: tss.v1.GetOperationResponse.signing_result:type_name -> tss.v1.SigningResult
	4,  // 12: tss.v1.GetOperationResponse.resharing_result:type_name -> tss.v1.KeygenResult
	2,  // 13: tss.v1.GetOperationResponse.keygen_request:type_name -> tss.v1.StartKeygenRequest
	5,  // 14: tss.v1.GetOperationResponse.signing_request:type_name -> tss.v1.StartSigningRequest
	8,  // 15: tss.v1.GetOperationResponse.resharing_request:type_name -> tss.v1.StartResharingRequest
	2,  // 16: tss.v1.TSSService.StartKeygen:input_type -> tss.v1.StartKeygenRequest
	5,  // 17: tss.v1.TSSService.StartSigning:input_type -> tss.v1.StartSigningRequest
	8,  // 18: tss.v1.TSSService.StartResharing:input_type -> tss.v1.StartResharingRequest
	10, // 19: tss.v1.TSSService.GetOperation:input_type -> tss.v1.GetOperationRequest
	3,  // 20: tss.v1.TSSService.StartKeygen:output_type -> tss.v1.StartKeygenResponse
	6,  // 21: tss.v1.TSSService.StartSigning:output_type -> tss.v1.StartSigningResponse
	9,  // 22: tss.v1.TSSService.StartResharing:output_type -> tss.v1.StartResharingResponse
	11, // 23: tss.v1.TSSService.GetOperation:output_type -> tss.v1.GetOperationResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_tss_v1_tss_proto_init() }
func file_proto_tss_v1_tss_proto_init() {
	if File_proto_tss_v1_tss_proto != nil {
		return
	}
	file_proto_tss_v1_tss_proto_msgTypes[9].OneofWrappers = []any{
		(*GetOperationResponse_KeygenResult)(nil),
		(*GetOperationResponse_SigningResult)(nil),
		(*GetOperationResponse_ResharingResult)(nil),
		(*GetOperationResponse_KeygenRequest)(nil),
		(*GetOperationResponse_SigningRequest)(nil),
		(*GetOperationResponse_ResharingRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tss_v1_tss_proto_rawDesc), len(file_proto_tss_v1_tss_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tss_v1_tss_proto_goTypes,
		DependencyIndexes: file_proto_tss_v1_tss_proto_depIdxs,
		EnumInfos:         file_proto_tss_v1_tss_proto_enumTypes,
		MessageInfos:      file_proto_tss_v1_tss_proto_msgTypes,
	}.Build()
	File_proto_tss_v1_tss_proto = out.File
	file_proto_tss_v1_tss_proto_goTypes = nil
	file_proto_tss_v1_tss_proto_depIdxs = nil
}
