#!/bin/bash

# DKNet TSS Complete Test Suite
# This script runs both keygen and signing tests in sequence

set -e

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/test-common.sh"

# Configuration: Enable/disable resharing tests
# Set to "true" to enable resharing tests, "false" to skip them
ENABLE_RESHARING_TESTS="false"

# Function to run complete test suite (test only, requires environment to be started)
run_complete_tests() {
    print_status "Starting DKNet TSS Complete Test Suite"
    echo "========================================"
    
    # Display test environment info
    display_test_env_info
    echo ""
    
    # Check environment (do not start automatically)
    check_test_env
    
    # Test validation service first
    if test_validation_service "Hello World from Complete Test Suite"; then
        print_success "✓ Validation service test passed"
    else
        print_error "✗ Validation service test failed"
        return 1
    fi
    
    echo ""
    
    # Phase 1: Run keygen tests
    print_status "Phase 1: Running Keygen Tests"
    echo "=============================="
    
    # Import keygen test functions
    source "$SCRIPT_DIR/test-keygen.sh"
    
    # Test 1: Simple 2-of-3 keygen
    local key_id_1
    if key_id_1=$(test_keygen 1 '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'", "'$NODE3_PEER_ID'"' "2-of-3 threshold keygen"); then
        print_success "✓ Keygen Test 1 passed"
    else
        print_error "✗ Keygen Test 1 failed"
        return 1
    fi
    
    echo ""
    
    # Test 2: 3-of-3 keygen
    local key_id_2
    if key_id_2=$(test_keygen 2 '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'", "'$NODE3_PEER_ID'"' "3-of-3 threshold keygen"); then
        print_success "✓ Keygen Test 2 passed"
    else
        print_error "✗ Keygen Test 2 failed"
        return 1
    fi
    
    echo ""
    
    # Test 3: 2-node keygen
    local key_id_3
    if key_id_3=$(test_keygen 1 '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'"' "2-of-2 threshold keygen"); then
        print_success "✓ Keygen Test 3 passed"
    else
        print_error "✗ Keygen Test 3 failed"
        return 1
    fi
    
    echo ""
    
    print_success "All keygen tests completed successfully!"
    
    # Save key IDs for resharing and signing tests
    echo "$key_id_1" > /tmp/dknet-key-1.txt
    echo "$key_id_2" > /tmp/dknet-key-2.txt
    echo "$key_id_3" > /tmp/dknet-key-3.txt
    
    echo ""
    print_status "Phase 2: Running Resharing Tests"
    echo "================================="
    
    if [ "$ENABLE_RESHARING_TESTS" = "true" ]; then
        # Import resharing test functions
        source "$SCRIPT_DIR/test-resharing.sh"
        
        # Run resharing tests (they will load key IDs automatically)
        local resharing_results
        if resharing_results=$(run_resharing_tests); then
            print_success "All resharing tests completed successfully!"
        else
            print_error "Resharing tests failed"
            return 1
        fi
    else
        print_status "⚠️  Resharing tests are currently disabled"
        print_status "   Reason: TSS library v2.0.2 has known issues with resharing operations"
        print_status "   To enable: Set ENABLE_RESHARING_TESTS=\"true\" in this script"
        print_status "   Skipping resharing tests and creating empty placeholder files..."
        
        # Create empty placeholder files for resharing results
        echo "" > /tmp/dknet-key-reshared-1.txt
        echo "" > /tmp/dknet-key-reshared-2.txt
        
        print_success "✓ Resharing tests skipped successfully"
    fi
    
    echo ""
    print_status "Phase 3: Running Signing Tests"
    echo "==============================="
    
    # Import signing test functions
    source "$SCRIPT_DIR/test-signing.sh"
    
    # Load key IDs from files (generated by keygen and resharing tests)
    # Extract only the key ID (last line) from the files
    KEY_ID_1=$(tail -1 /tmp/dknet-key-1.txt 2>/dev/null | tr -d '\n\r' || echo "")
    KEY_ID_2=$(tail -1 /tmp/dknet-key-2.txt 2>/dev/null | tr -d '\n\r' || echo "")
    KEY_ID_3=$(tail -1 /tmp/dknet-key-3.txt 2>/dev/null | tr -d '\n\r' || echo "")
    KEY_ID_RESHARED_1=$(tail -1 /tmp/dknet-key-reshared-1.txt 2>/dev/null | tr -d '\n\r' || echo "")
    KEY_ID_RESHARED_2=$(tail -1 /tmp/dknet-key-reshared-2.txt 2>/dev/null | tr -d '\n\r' || echo "")
    
    print_result "Using Generated Key IDs:"
    print_result "  - Key 1 (2-of-3): $KEY_ID_1"
    print_result "  - Key 2 (3-of-3): $KEY_ID_2"
    print_result "  - Key 3 (2-of-2): $KEY_ID_3"
    print_result "  - Reshared Key 1 (3-of-3): $KEY_ID_RESHARED_1"
    print_result "  - Reshared Key 2 (2-of-3): $KEY_ID_RESHARED_2"
    echo ""
    
    # Test 1: Sign with 2-of-3 key using 2 participants
    local signature_1
    if signature_1=$(test_signing "$KEY_ID_1" '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'"' "Hello World Test 1" "2-of-3 key with 2 participants"); then
        print_success "✓ Signing Test 1 passed"
    else
        print_error "✗ Signing Test 1 failed"
        return 1
    fi
    
    echo ""
    
    # Add a short delay between tests to avoid resource conflicts
    sleep 2
    
    # Test 2: Sign with 2-of-3 key using different 2 participants
    local signature_2
    if signature_2=$(test_signing "$KEY_ID_1" '"'$NODE2_PEER_ID'", "'$NODE3_PEER_ID'"' "Hello World Test 2" "2-of-3 key with different 2 participants"); then
        print_success "✓ Signing Test 2 passed"
    else
        print_error "✗ Signing Test 2 failed"
        return 1
    fi
    
    echo ""
    
    # Add a short delay between tests
    sleep 2
    
    # Test 3: Sign with 3-of-3 key using all 3 participants
    local signature_3
    if signature_3=$(test_signing "$KEY_ID_2" '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'", "'$NODE3_PEER_ID'"' "Hello World Test 3" "3-of-3 key with all participants"); then
        print_success "✓ Signing Test 3 passed"
    else
        print_error "✗ Signing Test 3 failed"
        return 1
    fi
    
    echo ""
    
    # Add a short delay between tests
    sleep 2
    
    # Test 4: Sign with 2-of-2 key using both participants
    local signature_4
    if signature_4=$(test_signing "$KEY_ID_3" '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'"' "Hello World Test 4" "2-of-2 key with both participants"); then
        print_success "✓ Signing Test 4 passed"
    else
        print_error "✗ Signing Test 4 failed"
        return 1
    fi
    
    echo ""
    
    # Test 5: Sign with reshared key (3-of-3) - only if resharing was enabled
    local signature_5=""
    if [ "$ENABLE_RESHARING_TESTS" = "true" ] && [ -n "$KEY_ID_RESHARED_1" ]; then
        if signature_5=$(test_signing "$KEY_ID_RESHARED_1" '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'", "'$NODE3_PEER_ID'"' "Hello World Test 5" "Reshared 3-of-3 key"); then
            print_success "✓ Signing Test 5 passed"
        else
            print_error "✗ Signing Test 5 failed"
            return 1
        fi
    else
        print_status "⚠️  Signing Test 5 skipped (resharing disabled or no reshared key)"
        signature_5="SKIPPED"
    fi
    
    echo ""
    
    # Test 6: Sign with reshared key (2-of-3) - only if resharing was enabled
    local signature_6=""
    if [ "$ENABLE_RESHARING_TESTS" = "true" ] && [ -n "$KEY_ID_RESHARED_2" ]; then
        if signature_6=$(test_signing "$KEY_ID_RESHARED_2" '"'$NODE1_PEER_ID'", "'$NODE3_PEER_ID'"' "Hello World Test 6" "Reshared 2-of-3 key"); then
            print_success "✓ Signing Test 6 passed"
        else
            print_error "✗ Signing Test 6 failed"
            return 1
        fi
    else
        print_status "⚠️  Signing Test 6 skipped (resharing disabled or no reshared key)"
        signature_6="SKIPPED"
    fi
    
    echo ""
    
    # Test 7: Sign different message types
    local signature_7
    if signature_7=$(test_signing "$KEY_ID_1" '"'$NODE1_PEER_ID'", "'$NODE2_PEER_ID'"' "Transaction: Send 100 ETH to 0x123..." "Transaction signing test"); then
        print_success "✓ Signing Test 7 passed"
    else
        print_error "✗ Signing Test 7 failed"
        return 1
    fi
    
    echo ""
    
    # Test 8: Sign JSON message
    local json_message='{"type":"transfer","amount":"100","to":"0x123","nonce":42}'
    local signature_8
    if signature_8=$(test_signing "$KEY_ID_1" '"'$NODE2_PEER_ID'", "'$NODE3_PEER_ID'"' "$json_message" "JSON message signing test"); then
        print_success "✓ Signing Test 8 passed"
    else
        print_error "✗ Signing Test 8 failed"
        return 1
    fi
    
    print_success "All signing tests completed successfully!"
    
    echo ""
    echo "========================================"
    print_success "🎉 Complete Test Suite Finished Successfully!"
    echo "========================================"
    
    # Final Summary
    print_result "Complete Test Summary:"
    echo ""
    print_result "Keygen Results:"
    print_result "  - Original Key 1 (2-of-3): $KEY_ID_1"
    print_result "  - Original Key 2 (3-of-3): $KEY_ID_2"
    print_result "  - Original Key 3 (2-of-2): $KEY_ID_3"
    print_result "Resharing Results:"
    print_result "  - Reshared Key 1 (3-of-3): $KEY_ID_RESHARED_1"
    print_result "  - Reshared Key 2 (2-of-3): $KEY_ID_RESHARED_2"
    echo ""
    print_result "Signing Results:"
    print_result "  - Test 1 Signature: $signature_1"
    print_result "  - Test 2 Signature: $signature_2"
    print_result "  - Test 3 Signature: $signature_3"
    print_result "  - Test 4 Signature: $signature_4"
    print_result "  - Test 5 Signature: $signature_5"
    print_result "  - Test 6 Signature: $signature_6"
    print_result "  - Test 7 Signature: $signature_7"
    print_result "  - Test 8 Signature: $signature_8"
    echo ""
    print_result "Authentication:"
    print_result "  - JWT Token: $JWT_TOKEN"
    echo ""
    if [ "$ENABLE_RESHARING_TESTS" = "true" ]; then
        print_result "Total Tests: 17 (3 keygen + 4 resharing + 8 signing + 2 validation)"
    else
        print_result "Total Tests: 13 (3 keygen + 6 signing + 2 validation + 2 resharing skipped)"
    fi
    print_result "All operations completed successfully ✓"
}

# Function to run keygen only
run_keygen_only() {
    print_status "Running Keygen Tests Only"
    echo "=========================="
    
    # Check environment (do not start automatically)
    check_test_env
    
    # Run keygen tests from the keygen script
    "$SCRIPT_DIR/test-keygen.sh" test
}

# Function to run resharing only
run_resharing_only() {
    print_status "Running Resharing Tests Only"
    echo "============================"
    
    if [ "$ENABLE_RESHARING_TESTS" = "true" ]; then
        # Check environment
        check_test_env
        
        # Run resharing tests from the resharing script
        "$SCRIPT_DIR/test-resharing.sh" test
    else
        print_status "⚠️  Resharing tests are currently disabled"
        print_status "   Reason: TSS library v2.0.2 has known issues with resharing operations"
        print_status "   To enable: Set ENABLE_RESHARING_TESTS=\"true\" in this script"
        print_error "Cannot run resharing tests - they are disabled"
        return 1
    fi
}

# Function to run signing only
run_signing_only() {
    print_status "Running Signing Tests Only"
    echo "==========================="
    
    # Check environment
    check_test_env
    
    # Run signing tests from the signing script
    "$SCRIPT_DIR/test-signing.sh" test
}

# Function to show help
show_help() {
    echo "DKNet TSS Complete Test Suite"
    echo ""
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  start              Start test environment"
    echo "  test               Run complete test suite (keygen + resharing + signing)"
    echo "  all                Same as 'test' - run complete test suite"
    echo "  keygen             Run keygen tests only"
    echo "  resharing          Run resharing tests only (requires keygen first)"
    echo "  signing            Run signing tests only (requires keygen and resharing first)"
    echo "  status             Show environment status"
    echo "  logs               Show logs for all services"
    echo "  logs <service>     Show logs for specific service"
    echo "  stop               Stop test environment"
    echo "  cleanup            Stop environment and cleanup resources"
    echo "  help               Show this help message"
    echo ""
    echo "Prerequisites:"
    echo "  - Docker and docker-compose must be installed"
    echo "  - Go must be installed for JWT token generation"
    echo "  - curl and jq must be available for API testing"
    echo ""
    echo "Examples:"
    echo "  $0 start           # Start test environment"
    echo "  $0 test            # Run complete test suite (default)"
    echo "  $0 keygen          # Run keygen tests only"
    echo "  $0 resharing       # Run resharing tests only"
    echo "  $0 signing         # Run signing tests only"
    echo "  $0 status          # Check environment status"
    echo "  $0 logs tss-node1  # Show node1 logs"
    echo "  $0 cleanup         # Cleanup everything"
    echo ""
    echo "Typical Test Flow:"
    echo "  1. $0 start        # Start Docker test environment"
    echo "  2. $0 test         # Run complete test suite"
    echo "  3. $0 cleanup      # Cleanup environment"
    echo ""
    echo "Or step by step:"
    echo "  1. $0 start        # Start environment"
    echo "  2. $0 keygen       # Run keygen tests"
    echo "  3. $0 resharing    # Run resharing tests"
    echo "  4. $0 signing      # Run signing tests"
    echo "  5. $0 cleanup      # Cleanup environment"
}

# Main script logic
main() {
    case "${1:-test}" in
        start)
            start_test_env
            ;;
        test|all)
            run_complete_tests
            ;;
        keygen)
            run_keygen_only
            ;;
        resharing)
            run_resharing_only
            ;;
        signing)
            run_signing_only
            ;;
        status)
            show_test_env_status
            echo ""
            if [ -n "$JWT_TOKEN" ]; then
                print_result "Current JWT Token: $JWT_TOKEN"
            fi
            ;;
        logs)
            show_test_env_logs "$2"
            ;;
        stop)
            stop_test_env
            ;;
        cleanup)
            cleanup_test_env
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            print_error "Unknown command: $1"
            echo ""
            show_help
            exit 1
            ;;
    esac
}

# Run main function with all arguments
main "$@" 